package com.oopproject.VirtualStockMarketSimulator.repository;

import com.oopproject.VirtualStockMarketSimulator.model.StockPriceHistory;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface StockPriceHistoryRepository extends JpaRepository<StockPriceHistory, Long> {

    // This is the magic method. If this is missing, the Controller crashes.
    List<StockPriceHistory> findByStockId(Long stockId);

}
/*
 * StockPriceHistoryRepository
 *
 * This is the **data access layer** for StockPriceHistory entities.
 * It connects your Java code to the 'stock_price_history' table in the database.
 *
 * Key Points:
 * 1. Spring Data JPA automatically implements this interface at runtime, so you don't write SQL manually.
 * 2. Extending JpaRepository<StockPriceHistory, Long> gives access to built-in CRUD operations:
 *      - save(entity) → insert or update a record
 *      - findById(id) → retrieve a record by primary key
 *      - findAll() → retrieve all records
 *      - delete(entity) → delete a record
 * 3. You can also define custom query methods by simply writing their signatures.
 *    Spring will automatically generate the SQL for these based on the method name.
 *
 * Example usage of this repository:
 *   - Saving new price points generated by the simulation
 *   - Fetching historical prices for a stock to display in a chart
 *
 * Relationships:
 *  - StockPriceHistory entries are linked to a Stock entity via a foreign key (stock_id).
 *    This repository lets you query price history efficiently without raw SQL.
 *
 * Annotation:
 *  - @Repository marks this interface as a Spring bean for data access.
 */


    /*
     * Finds all StockPriceHistory entries for a given stock ID.
     * Used to build price charts and analyze historical data.
     *
     * Generated SQL example:
     *      SELECT * FROM stock_price_history WHERE stock_id = ?;
     *
     * @param stockId The ID of the stock whose price history is requested.
     * @return A list of StockPriceHistory entries for the specified stock.
     */



